"""Domain Layer - pure businesse logic, framework- and infrastructure-agnostic.

CODE IN THIS PACKAGE MUST NO IMPORT FROM FASTAPI, SQLALCHEMY, OR ANY CONCRETE INFRASTRUCTURE ADAPTER. 
DEPENDENCIES FLOW INWARD: OUTER LAYERS DEPENDE ON THIS ONE, NEVER THE OTHER WAY AROUND."""
